### ISSUE TITLE
Is it compatible with Next theme?

### ISSUE THREAD

**Issue by MeowSalty** [miao1007/hexo-filter-kroki#4]
I tried to use this plugin on my blog, but after installation it was not replaced with images, it was still code blocks.

This is my page: https://blog.fishfish.date/2024/03/08/Easy_Live_%E7%94%B5%E7%8E%A9%E9%A3%9E%E6%9C%BA%E6%9D%AF%E6%B5%8B%E8%AF%84%EF%BC%9A%E5%B9%B6%E5%B0%9D%E8%AF%95%E7%A0%B4%E8%A7%A3%E4%B8%80%E4%B8%8B%E5%AE%83/#%E5%88%86%E6%9E%90%E7%BB%93%E6%9E%9C

My config file:

```yaml
kroki:
  # the kroki free service server, you may switch to your self-hosted sever.
  server: "https://kroki.io/"
  # Available values 
  # "inline": <svg>xxx<svg/>
  # "inlineUrlEncode": <img src='data:image/svg+xml;> 
  # "inlineBase64": <img src='data:image/svg+xml;base64> 
  # "localLink": <img src="/assert/puml/xxxx.svg">
  # "externalLink": <img src="https://kroki.io/plantuml/svg/xxx">
  link: "localLink"

  # common options: svg/png
  outputFormat: "png"
  # the generated img will have a default class name.
  className: 'kroki'

  # append some fragment per diagram, used for the theme or else config
  inserts:
    - diagram: plantuml
      after: 1
      # see https://plantuml.com/en/theme
      fragment: '!theme sketchy-outline'
    - diagram: mermaid
      after: 0
      # see https://mermaid-js.github.io/mermaid/#/theming
      fragment: "%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ff0000'}}}%%"
```
